CREATE TABLE support_usage (
  student_id INTEGER,
  has_used_counseling_services BOOLEAN,
  satisfaction_with_support_services INTEGER,
  preferred_support_method TEXT,
  FOREIGN KEY (student_id) REFERENCES students(student_id)
);
INSERT INTO support_usage VALUES (1, True, 8, 'In-person');
INSERT INTO support_usage VALUES (2, False, 5, 'Online');
INSERT INTO support_usage VALUES (3, False, 2, 'Online');
INSERT INTO support_usage VALUES (4, False, 2, 'In-person');
INSERT INTO support_usage VALUES (5, True, 6, 'Peer support');
INSERT INTO support_usage VALUES (6, True, 9, 'In-person');
INSERT INTO support_usage VALUES (7, False, 1, 'Online');
INSERT INTO support_usage VALUES (8, False, 6, 'In-person');
INSERT INTO support_usage VALUES (9, False, 9, 'Online');
INSERT INTO support_usage VALUES (10, True, 8, 'Online');
INSERT INTO support_usage VALUES (11, False, 6, 'Peer support');
INSERT INTO support_usage VALUES (12, False, 3, 'Online');
INSERT INTO support_usage VALUES (13, False, 8, 'Online');
INSERT INTO support_usage VALUES (14, True, 9, 'Peer support');
INSERT INTO support_usage VALUES (15, False, 1, 'Online');
INSERT INTO support_usage VALUES (16, False, 9, 'Peer support');
INSERT INTO support_usage VALUES (17, False, 6, 'Peer support');
INSERT INTO support_usage VALUES (18, False, 6, 'Online');
INSERT INTO support_usage VALUES (19, False, 4, 'Online');
INSERT INTO support_usage VALUES (20, False, 1, 'In-person');
INSERT INTO support_usage VALUES (21, True, 10, 'Peer support');
INSERT INTO support_usage VALUES (22, False, 8, 'In-person');
INSERT INTO support_usage VALUES (23, False, 2, 'Online');
INSERT INTO support_usage VALUES (24, True, 1, 'In-person');
INSERT INTO support_usage VALUES (25, False, 2, 'Peer support');
INSERT INTO support_usage VALUES (26, False, 1, 'In-person');
INSERT INTO support_usage VALUES (27, True, 1, 'Peer support');
INSERT INTO support_usage VALUES (28, False, 9, 'Online');
INSERT INTO support_usage VALUES (29, False, 1, 'Online');
INSERT INTO support_usage VALUES (30, False, 4, 'Peer support');
INSERT INTO support_usage VALUES (31, True, 10, 'Online');
INSERT INTO support_usage VALUES (32, False, 6, 'Online');
INSERT INTO support_usage VALUES (33, False, 7, 'Online');
INSERT INTO support_usage VALUES (34, False, 2, 'Online');
INSERT INTO support_usage VALUES (35, False, 6, 'Peer support');
INSERT INTO support_usage VALUES (36, True, 7, 'In-person');
INSERT INTO support_usage VALUES (37, False, 10, 'In-person');
INSERT INTO support_usage VALUES (38, True, 10, 'Online');
INSERT INTO support_usage VALUES (39, True, 2, 'In-person');
INSERT INTO support_usage VALUES (40, False, 2, 'In-person');
INSERT INTO support_usage VALUES (41, False, 10, 'Online');
INSERT INTO support_usage VALUES (42, False, 7, 'Online');
INSERT INTO support_usage VALUES (43, False, 1, 'In-person');
INSERT INTO support_usage VALUES (44, False, 8, 'Peer support');
INSERT INTO support_usage VALUES (45, True, 3, 'Online');
INSERT INTO support_usage VALUES (46, False, 6, 'Peer support');
INSERT INTO support_usage VALUES (47, False, 9, 'In-person');
INSERT INTO support_usage VALUES (48, False, 6, 'Online');
INSERT INTO support_usage VALUES (49, True, 9, 'Peer support');
INSERT INTO support_usage VALUES (50, False, 7, 'Online');
INSERT INTO support_usage VALUES (51, False, 9, 'In-person');
INSERT INTO support_usage VALUES (52, True, 2, 'Peer support');
INSERT INTO support_usage VALUES (53, True, 8, 'In-person');
INSERT INTO support_usage VALUES (54, False, 8, 'In-person');
INSERT INTO support_usage VALUES (55, False, 2, 'Online');
INSERT INTO support_usage VALUES (56, True, 4, 'Peer support');
INSERT INTO support_usage VALUES (57, False, 7, 'In-person');
INSERT INTO support_usage VALUES (58, True, 4, 'In-person');
INSERT INTO support_usage VALUES (59, False, 4, 'Peer support');
INSERT INTO support_usage VALUES (60, False, 6, 'In-person');
INSERT INTO support_usage VALUES (61, False, 10, 'In-person');
INSERT INTO support_usage VALUES (62, False, 6, 'Peer support');
INSERT INTO support_usage VALUES (63, False, 10, 'Peer support');
INSERT INTO support_usage VALUES (64, True, 3, 'Peer support');
INSERT INTO support_usage VALUES (65, False, 9, 'Peer support');
INSERT INTO support_usage VALUES (66, False, 10, 'Online');
INSERT INTO support_usage VALUES (67, False, 2, 'Peer support');
INSERT INTO support_usage VALUES (68, True, 6, 'Online');
INSERT INTO support_usage VALUES (69, True, 7, 'Online');
INSERT INTO support_usage VALUES (70, True, 9, 'Online');
INSERT INTO support_usage VALUES (71, False, 3, 'In-person');
INSERT INTO support_usage VALUES (72, False, 10, 'Online');
INSERT INTO support_usage VALUES (73, False, 3, 'Online');
INSERT INTO support_usage VALUES (74, False, 7, 'In-person');
INSERT INTO support_usage VALUES (75, False, 4, 'In-person');
INSERT INTO support_usage VALUES (76, True, 8, 'In-person');
INSERT INTO support_usage VALUES (77, False, 7, 'Peer support');
INSERT INTO support_usage VALUES (78, False, 5, 'In-person');
INSERT INTO support_usage VALUES (79, False, 7, 'In-person');
INSERT INTO support_usage VALUES (80, False, 3, 'Online');
INSERT INTO support_usage VALUES (81, False, 2, 'In-person');
INSERT INTO support_usage VALUES (82, False, 6, 'Peer support');
INSERT INTO support_usage VALUES (83, True, 2, 'In-person');
INSERT INTO support_usage VALUES (84, True, 3, 'Peer support');
INSERT INTO support_usage VALUES (85, False, 6, 'In-person');
INSERT INTO support_usage VALUES (86, False, 5, 'In-person');
INSERT INTO support_usage VALUES (87, False, 8, 'In-person');
INSERT INTO support_usage VALUES (88, False, 9, 'In-person');
INSERT INTO support_usage VALUES (89, True, 3, 'Peer support');
INSERT INTO support_usage VALUES (90, True, 10, 'Peer support');
INSERT INTO support_usage VALUES (91, False, 3, 'Online');
INSERT INTO support_usage VALUES (92, False, 3, 'Peer support');
INSERT INTO support_usage VALUES (93, True, 6, 'In-person');
INSERT INTO support_usage VALUES (94, False, 1, 'Online');
INSERT INTO support_usage VALUES (95, True, 7, 'Online');
INSERT INTO support_usage VALUES (96, False, 1, 'Online');
INSERT INTO support_usage VALUES (97, True, 5, 'In-person');
INSERT INTO support_usage VALUES (98, False, 10, 'Peer support');
INSERT INTO support_usage VALUES (99, False, 8, 'In-person');
INSERT INTO support_usage VALUES (100, False, 4, 'Online');